get_setup_details: workaround a issue
  Traceback (most recent call last):
    File "sdcm/tester.py", line 129, in wrapper
      return method(*args, **kwargs)
    File "sdcm/tester.py", line 232, in setUp
      self.stats['setup_details'] = self.get_setup_details()
    File "sdcm/tester.py", line 997, in get_setup_details
      p[2] = re.sub('\s', '_', p[2])
  TypeError: 'tuple' object does not support item assignment

Signed-off-by: Amos Kong <amos@scylladb.com>